---

   - name: Create config
     template: src=server.cnf.j2 dest=/etc/my.cnf.d/server.cnf owner=root mode=0644

   - name: Stop MySQL
     service: name=mysql state=stopped

   - name: Start Cluster
     shell: sudo /etc/init.d/mysql start --wsrep-new-cluster
